services:
  - type: web
    name: resgatando-vidas-4-patas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ong.wsgi
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
    postDeployCommand: |
      python manage.py migrate

postDeployCommand: |
  python manage.py migrate
  echo "from django.contrib.auth import get_user_model; User=get_user_model(); User.objects.filter(username='ÉosD').exists() or User.objects.create_superuser('ÉosD','raicarvalho343@gmail.com','G@tinho')" | python manage.py shell
